#!/bin/sh

case "$1" in
	start)
		# start logging service before everything else
		echo "Starting system logging."
		syslogd -s 1000 -b 4 -O /LF/Base/FR/frlog
		if [ $? -gt 0 ]; then
		# echo "syslogd failed to start ...!"
			logger -s -t "Emerald Base" -p local4.err  "syslogd failed to start ...!"
		fi
		(
			sleep 0.2; klogd
			if [ $? -gt 0 ]; then
			# echo "klogd failed to start ... !"
				logger -s -t "Emerald Base" -p local4.err  "klogd failed to start ... !"
			fi
			) &
		;;
	stop)
		logger -s -t "Emerald Base" -p local4.notice  "Stopping system logging ... !"
		killall klogd
		killall syslogd
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
