#!/bin/sh

# This script mounts misc volumes late (after AppManager starts)

DAVE=/tmp/bulk_ready

report ()
{
	if [ $1 = 0 ]; then
		echo "Success"
	else
		#echo $2
		logger -s -t "Emerald Base" -p local4.err $2
	fi
}

tuneup ()
{
	logger -s -t "/etc/init.d/mounts" -p local4.notice "Failed bulk mount.  We're sick... tune up!  Setting panic to 3"
	echo 3 > /sys/devices/platform/lf1000-gpio/panic
	# Force a reboot that does not run /etc/init.d/shutdown, which will clear panic.  
	# See similar code in the old /usr/bin/app.  Not there now.
	sync
	sleep 1
	reboot -f
}

BULK=/LF/Bulk

case "$1" in
	start)
		logger -s -t "Emerald Base" -p local4.notice `tim begin "Attaching Bulk"`
		mn=`awk -F: '/Bulk/ {print substr($1,4)}' /proc/mtd`
		ud=1
		ubiattach /dev/ubi_ctrl -d $ud -m $mn
		if [ $? = 0 ]; then
			where=$BULK
			uv=ubi_bulk
			logger -s -t "Emerald Base" -p local4.notice `tim begin "Mounting $where"`
			mount -t ubifs -o rw ubi${ud}:${uv} $where
			RES=$?
			# Tell Dave!  1=bulk is ready and good, 0 is it will never be ready,
			# and no file is not ready yet.
			echo $((!RES)) > $DAVE
			report $RES "Failed mount of ubi${ud}:${uv} to $where"
			if [ $RES != 0 ]; then
				tuneup
			fi
		else
			# echo "Failed ubiattach for mtd$mn!"
			logger -s -t "Emerald Base" -p local4.err "Failed ubiattach for mtd$mn!"
			tuneup
			echo 0 > $DAVE
		fi
		tim done "Mounting $where"
		;;
	stop)
		logger -s -t "Emerald Base" -p local4.notice "umount bulk... !"
		ud=1
		if mount | grep $BULK > /dev/null; then umount $BULK; fi
		report $? "Failed umount of ubi${ud} from $BULK"
		if [ -e /sys/class/ubi/ubi$ud ]; then
			ubidetach /dev/ubi_ctrl -d $ud
		fi
		rm -f $DAVE
		;;

	restart)
		logger -s -t "Emerald Base" -p local4.notice "restart mounting bulk... !"	
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
