#!/bin/sh

tim begin "Shutting down system"
# stop zeroconf
## Stopping avahi-daemon is sending SIGTERM to our process and killing us!
## Commenting it out
# /etc/init.d/avahi-daemon stop
/etc/init.d/dbus-1 stop
tim done "dbus-1 stop"
/etc/init.d/vsftpd stop
tim done "vsftpd stop"
/etc/init.d/telnetd stop
tim done "telnetd stop"
/etc/init.d/vbus stop
tim done "vbus stop"
/etc/init.d/networking stop
tim done "networking stop"
/etc/init.d/usbether stop
tim done "usbether stop"

if [ `cat /sys/devices/platform/lf1000-gpio/boot_image` = "RECOVERY" ]; then
	/usr/bin/recovery-shutdown
	# Exit so we don't clear this later in script
	exit 0
elif [ `cat /sys/devices/platform/lf1000-gpio/request` = "UPDATE" ]; then
	# FW update reboot
	echo "FW update reboot"
	logger -s -t "Emerald Base" -p local4.notice  "FW Update Reboot ... !"	
elif [ `cat /sys/devices/platform/lf1000-gpio/request` = "SHORT" ]; then
	# Short circuit play boot
	echo Short Circuit Shutdown
	logger -s -t "Emerald Base" -p local4.notice  "Short Circuit Shutdown ... !"	
else
	# Play mode on RSF1
	# save volume setting if touchscreen unit, ie no volume slider
	TOUCHSCREEN="/sys/devices/platform/lf1000-gpio/touchscreen"
	if [ -e ${TOUCHSCREEN} -a `cat ${TOUCHSCREEN}` = "YES" ] ; then
		vol=`cat /sys/devices/platform/lf1000-audio/volume`
		if [ $vol -eq 0 ]; then
			vol=383
		fi
		echo $vol > /flags/volume
	fi

	# KillApp
	tim begin "killall mainapp"
	killall app AppManager CartManager
	tim done "killall mainapp"

	# echo "Stopping system logging"
	/etc/init.d/flight-recorder stop
fi

# Request play
if [ ! `cat /sys/devices/platform/lf1000-gpio/request` = "UPDATE" ]; then
	echo "PLAY" > /sys/devices/platform/lf1000-gpio/request
fi

# Announce clean shutdown before umount of sys
echo "CLEAN" > /sys/devices/platform/lf1000-gpio/shutdown

# Clear panic counter
echo 0 > /sys/devices/platform/lf1000-gpio/panic

# unmount file systems
tim begin "umount -a"
umount -a

# XXX: power off the screen
#mlc-control /dev/mlc s enable off
