#ifndef __GPIO_MAP_H__
#define __GPIO_MAP_H__

#include <gpio.h>

/*
 * DEV BOARD DEFINES
 */
#define DEV_LCD_RESET_PORT		GPIO_PORT_ALV
#define DEV_LCD_RESET_PIN		GPIO_PIN5
#define DEV_AUDIO_POWER_PORT		GPIO_PORT_ALV
#define DEV_AUDIO_POWER_PIN		GPIO_PIN6

#define DEV_CARTRIDGE_DETECT_PORT	GPIO_PORT_A
#define DEV_CARTRIDGE_DETECT_PIN	GPIO_PIN18

#define DEV_LED_ENA_PORT		GPIO_PORT_A
#define DEV_LED_ENA_PIN			GPIO_PIN30

#define DEV_TOUCHSCREEN_X1_PORT		GPIO_PORT_B
#define DEV_TOUCHSCREEN_X1_PIN		GPIO_PIN2
#define DEV_TOUCHSCREEN_Y1_PORT		GPIO_PORT_B
#define DEV_TOUCHSCREEN_Y1_PIN		GPIO_PIN3
#define DEV_TOUCHSCREEN_X2_PORT		GPIO_PORT_B
#define DEV_TOUCHSCREEN_X2_PIN		GPIO_PIN4
#define DEV_TOUCHSCREEN_Y2_PORT		GPIO_PORT_B
#define DEV_TOUCHSCREEN_Y2_PIN		GPIO_PIN5

#define DEV_HEADPHONE_JACK_PORT		GPIO_PORT_B
#define DEV_HEADPHONE_JACK_PIN		GPIO_PIN10

#define DEV_DPAD_LEFT_PORT		GPIO_PORT_C
#define DEV_DPAD_LEFT_PIN		GPIO_PIN0
#define DEV_DPAD_RIGHT_PORT		GPIO_PORT_C
#define DEV_DPAD_RIGHT_PIN		GPIO_PIN1
#define DEV_DPAD_UP_PORT		GPIO_PORT_C
#define DEV_DPAD_UP_PIN			GPIO_PIN2
#define DEV_DPAD_DOWN_PORT		GPIO_PORT_C
#define DEV_DPAD_DOWN_PIN		GPIO_PIN3
#define DEV_SHOULDER_RIGHT_PORT		GPIO_PORT_C
#define DEV_SHOULDER_RIGHT_PIN		GPIO_PIN4

#define DEV_SHOULDER_LEFT_PORT		GPIO_PORT_C
#define DEV_SHOULDER_LEFT_PIN		GPIO_PIN7
#define DEV_BUTTON_A_PORT		GPIO_PORT_C
#define DEV_BUTTON_A_PIN		GPIO_PIN8
#define DEV_BUTTON_B_PORT		GPIO_PORT_C
#define DEV_BUTTON_B_PIN		GPIO_PIN9
#define DEV_BUTTON_HOME_PORT		GPIO_PORT_C
#define DEV_BUTTON_HOME_PIN		GPIO_PIN10
#define DEV_BUTTON_HINT_PORT		GPIO_PORT_C
#define DEV_BUTTON_HINT_PIN		GPIO_PIN11
#define DEV_BUTTON_PAUSE_PORT		GPIO_PORT_C
#define DEV_BUTTON_PAUSE_PIN		GPIO_PIN12
#define DEV_BUTTON_BRIGHTNESS_PORT	GPIO_PORT_C
#define DEV_BUTTON_BRIGHTNESS_PIN	GPIO_PIN13

#define DEV_EXT_POWER_PORT		GPIO_PORT_C
#define DEV_EXT_POWER_PIN		GPIO_PIN14


/*
 * DIDJ BOARD DEFINES
 */
#define DIDJ_LCD_RESET_PORT		GPIO_PORT_ALV
#define DIDJ_LCD_RESET_PIN		GPIO_PIN5
#define DIDJ_AUDIO_POWER_PORT		GPIO_PORT_ALV
#define DIDJ_AUDIO_POWER_PIN		GPIO_PIN6

#define DIDJ_CARTRIDGE_DETECT_PORT	GPIO_PORT_A
#define DIDJ_CARTRIDGE_DETECT_PIN	GPIO_PIN18

#define DIDJ_LED_ENA_PORT		GPIO_PORT_A
#define DIDJ_LED_ENA_PIN		GPIO_PIN30

#define DIDJ_TOUCHSCREEN_X1_PORT	GPIO_PORT_B
#define DIDJ_TOUCHSCREEN_X1_PIN		GPIO_PIN2
#define DIDJ_TOUCHSCREEN_Y1_PORT	GPIO_PORT_B
#define DIDJ_TOUCHSCREEN_Y1_PIN		GPIO_PIN3
#define DIDJ_TOUCHSCREEN_X2_PORT	GPIO_PORT_B
#define DIDJ_TOUCHSCREEN_X2_PIN		GPIO_PIN4
#define DIDJ_TOUCHSCREEN_Y2_PORT	GPIO_PORT_B
#define DIDJ_TOUCHSCREEN_Y2_PIN		GPIO_PIN5

#define DIDJ_HEADPHONE_JACK_PORT	GPIO_PORT_B
#define DIDJ_HEADPHONE_JACK_PIN		GPIO_PIN10

#define DIDJ_DPAD_LEFT_PORT		GPIO_PORT_C
#define DIDJ_DPAD_LEFT_PIN		GPIO_PIN0
#define DIDJ_DPAD_RIGHT_PORT		GPIO_PORT_C
#define DIDJ_DPAD_RIGHT_PIN		GPIO_PIN1
#define DIDJ_DPAD_UP_PORT		GPIO_PORT_C
#define DIDJ_DPAD_UP_PIN		GPIO_PIN2
#define DIDJ_DPAD_DOWN_PORT		GPIO_PORT_C
#define DIDJ_DPAD_DOWN_PIN		GPIO_PIN3
#define DIDJ_SHOULDER_LEFT_PORT		GPIO_PORT_C
#define DIDJ_SHOULDER_LEFT_PIN		GPIO_PIN4

#define DIDJ_SHOULDER_RIGHT_PORT	GPIO_PORT_C
#define DIDJ_SHOULDER_RIGHT_PIN		GPIO_PIN7
#define DIDJ_BUTTON_A_PORT		GPIO_PORT_C
#define DIDJ_BUTTON_A_PIN		GPIO_PIN8
#define DIDJ_BUTTON_B_PORT		GPIO_PORT_C
#define DIDJ_BUTTON_B_PIN		GPIO_PIN9
#define DIDJ_BUTTON_HOME_PORT		GPIO_PORT_C
#define DIDJ_BUTTON_HOME_PIN		GPIO_PIN10
#define DIDJ_BUTTON_HINT_PORT		GPIO_PORT_C
#define DIDJ_BUTTON_HINT_PIN		GPIO_PIN11
#define DIDJ_BUTTON_PAUSE_PORT		GPIO_PORT_C
#define DIDJ_BUTTON_PAUSE_PIN		GPIO_PIN12
#define DIDJ_BUTTON_BRIGHTNESS_PORT	GPIO_PORT_C
#define DIDJ_BUTTON_BRIGHTNESS_PIN	GPIO_PIN13

#define DIDJ_EXT_POWER_PORT		GPIO_PORT_C
#define DIDJ_EXT_POWER_PIN		GPIO_PIN14


/*
 * ACORN BOARD DEFINES
 */
#define ACORN_TOUCHSCREEN_X1_PORT	GPIO_PORT_A
#define ACORN_TOUCHSCREEN_X1_PIN	GPIO_PIN11
#define ACORN_TOUCHSCREEN_Y1_PORT	GPIO_PORT_A
#define ACORN_TOUCHSCREEN_Y1_PIN	GPIO_PIN12
#define ACORN_TOUCHSCREEN_X2_PORT	GPIO_PORT_A
#define ACORN_TOUCHSCREEN_X2_PIN	GPIO_PIN13
#define ACORN_TOUCHSCREEN_Y2_PORT	GPIO_PORT_A
#define ACORN_TOUCHSCREEN_Y2_PIN	GPIO_PIN14

#define ACORN_CARTRIDGE_DETECT_PORT	GPIO_PORT_A
#define ACORN_CARTRIDGE_DETECT_PIN	GPIO_PIN18

#define ACORN_LED_ENA_PORT		GPIO_PORT_A
#define ACORN_LED_ENA_PIN		GPIO_PIN30

#define ACORN_DPAD_RIGHT_PORT		GPIO_PORT_C
#define ACORN_DPAD_RIGHT_PIN		GPIO_PIN0
#define ACORN_DPAD_DOWN_PORT		GPIO_PORT_C
#define ACORN_DPAD_DOWN_PIN		GPIO_PIN1
#define ACORN_BUTTON_HINT_PORT		GPIO_PORT_C
#define ACORN_BUTTON_HINT_PIN		GPIO_PIN2
#define ACORN_BUTTON_VOLUMEUP_PORT	GPIO_PORT_C
#define ACORN_BUTTON_VOLUMEUP_PIN	GPIO_PIN3
#define ACORN_BUTTON_VOLUMEDOWN_PORT	GPIO_PORT_C
#define ACORN_BUTTON_VOLUMEDOWN_PIN	GPIO_PIN4
#define ACORN_SHOULDER_RIGHT_PORT	GPIO_PORT_C
#define ACORN_SHOULDER_RIGHT_PIN	GPIO_PIN5
#define ACORN_BUTTON_B_PORT		GPIO_PORT_C
#define ACORN_BUTTON_B_PIN		GPIO_PIN6
#define ACORN_BUTTON_A_PORT		GPIO_PORT_C
#define ACORN_BUTTON_A_PIN		GPIO_PIN7
#define ACORN_BUTTON_BRIGHTNESS_PORT	GPIO_PORT_C
#define ACORN_BUTTON_BRIGHTNESS_PIN	GPIO_PIN8
#define ACORN_DPAD_LEFT_PORT		GPIO_PORT_C
#define ACORN_DPAD_LEFT_PIN		GPIO_PIN9
#define ACORN_SHOULDER_LEFT_PORT	GPIO_PORT_C
#define ACORN_SHOULDER_LEFT_PIN		GPIO_PIN10
#define ACORN_DPAD_UP_PORT		GPIO_PORT_C
#define ACORN_DPAD_UP_PIN		GPIO_PIN11
#define ACORN_BUTTON_PAUSE_PORT		GPIO_PORT_C
#define ACORN_BUTTON_PAUSE_PIN		GPIO_PIN12
#define ACORN_BUTTON_HOME_PORT		GPIO_PORT_C
#define ACORN_BUTTON_HOME_PIN		GPIO_PIN13

#define ACORN_EXT_POWER_PORT		GPIO_PORT_C
#define ACORN_EXT_POWER_PIN		GPIO_PIN14

#define ACORN_HEADPHONE_JACK_PORT	GPIO_PORT_C
#define ACORN_HEADPHONE_JACK_PIN	GPIO_PIN18

/*
 * EMERALD BOARD DEFINES
 */
#define EMERALD_TOUCHSCREEN_X1_PORT	GPIO_PORT_A
#define EMERALD_TOUCHSCREEN_X1_PIN	GPIO_PIN11
#define EMERALD_TOUCHSCREEN_Y1_PORT	GPIO_PORT_A
#define EMERALD_TOUCHSCREEN_Y1_PIN	GPIO_PIN12
#define EMERALD_TOUCHSCREEN_X2_PORT	GPIO_PORT_A
#define EMERALD_TOUCHSCREEN_X2_PIN	GPIO_PIN13
#define EMERALD_TOUCHSCREEN_Y2_PORT	GPIO_PORT_A
#define EMERALD_TOUCHSCREEN_Y2_PIN	GPIO_PIN14

#define EMERALD_CARTRIDGE_DETECT_PORT	GPIO_PORT_A
#define EMERALD_CARTRIDGE_DETECT_PIN	GPIO_PIN18

#define EMERALD_LED_ENA_PORT		GPIO_PORT_A
#define EMERALD_LED_ENA_PIN		GPIO_PIN30

#define EMERALD_DPAD_DOWN_PORT		GPIO_PORT_C
#define EMERALD_DPAD_DOWN_PIN		GPIO_PIN0
#define EMERALD_DPAD_RIGHT_PORT		GPIO_PORT_C
#define EMERALD_DPAD_RIGHT_PIN		GPIO_PIN1
#define EMERALD_BUTTON_VOLUMEDOWN_PORT	GPIO_PORT_C
#define EMERALD_BUTTON_VOLUMEDOWN_PIN	GPIO_PIN2
#define EMERALD_BUTTON_A_PORT		GPIO_PORT_C
#define EMERALD_BUTTON_A_PIN		GPIO_PIN3
#define EMERALD_BUTTON_PAUSE_PORT	GPIO_PORT_C
#define EMERALD_BUTTON_PAUSE_PIN	GPIO_PIN4
#define EMERALD_BUTTON_HINT_PORT	GPIO_PORT_C
#define EMERALD_BUTTON_HINT_PIN		GPIO_PIN5
#define EMERALD_SHOULDER_RIGHT_PORT	GPIO_PORT_C
#define EMERALD_SHOULDER_RIGHT_PIN	GPIO_PIN6
#define EMERALD_BUTTON_VOLUMEUP_PORT	GPIO_PORT_C
#define EMERALD_BUTTON_VOLUMEUP_PIN	GPIO_PIN7
#define EMERALD_DPAD_LEFT_PORT		GPIO_PORT_C
#define EMERALD_DPAD_LEFT_PIN		GPIO_PIN8
#define EMERALD_DPAD_UP_PORT		GPIO_PORT_C
#define EMERALD_DPAD_UP_PIN		GPIO_PIN9
#define EMERALD_BUTTON_BRIGHTNESS_PORT	GPIO_PORT_C
#define EMERALD_BUTTON_BRIGHTNESS_PIN	GPIO_PIN10
#define EMERALD_BUTTON_B_PORT		GPIO_PORT_C
#define EMERALD_BUTTON_B_PIN		GPIO_PIN11
#define EMERALD_BUTTON_HOME_PORT	GPIO_PORT_C
#define EMERALD_BUTTON_HOME_PIN		GPIO_PIN12
#define EMERALD_SHOULDER_LEFT_PORT	GPIO_PORT_C
#define EMERALD_SHOULDER_LEFT_PIN	GPIO_PIN13

#define EMERALD_EXT_POWER_PORT		GPIO_PORT_C
#define EMERALD_EXT_POWER_PIN		GPIO_PIN14

#define EMERALD_HEADPHONE_JACK_PORT	GPIO_PORT_C
#define EMERALD_HEADPHONE_JACK_PIN	GPIO_PIN18

/*
 * K2 BOARD DEFINES
 */
#define K2_TOUCHSCREEN_X1_PORT		GPIO_PORT_A
#define K2_TOUCHSCREEN_X1_PIN		GPIO_PIN11
#define K2_TOUCHSCREEN_Y1_PORT		GPIO_PORT_A
#define K2_TOUCHSCREEN_Y1_PIN		GPIO_PIN12
#define K2_TOUCHSCREEN_X2_PORT		GPIO_PORT_A
#define K2_TOUCHSCREEN_X2_PIN		GPIO_PIN13
#define K2_TOUCHSCREEN_Y2_PORT		GPIO_PORT_A
#define K2_TOUCHSCREEN_Y2_PIN		GPIO_PIN14

//#define K2_CARTRIDGE_DETECT_PORT	GPIO_PORT_A	/* no cartridge */
//#define K2_CARTRIDGE_DETECT_PIN	GPIO_PIN18

#define K2_LED_ENA_PORT			GPIO_PORT_A
#define K2_LED_ENA_PIN			GPIO_PIN30

#define K2_DPAD_DOWN_PORT		GPIO_PORT_C
#define K2_DPAD_DOWN_PIN		GPIO_PIN0
#define K2_DPAD_RIGHT_PORT		GPIO_PORT_C
#define K2_DPAD_RIGHT_PIN		GPIO_PIN1

#define K2_BUTTON_A_PORT		GPIO_PORT_C
#define K2_BUTTON_A_PIN			GPIO_PIN3

#define K2_BUTTON_HINT_PORT		GPIO_PORT_C
#define K2_BUTTON_HINT_PIN		GPIO_PIN5
#define K2_SHOULDER_RIGHT_PORT		GPIO_PORT_C
#define K2_SHOULDER_RIGHT_PIN		GPIO_PIN6

#define K2_BUTTON_RED_PORT		GPIO_PORT_C
#define K2_BUTTON_RED_PIN		GPIO_PIN7

#define K2_DPAD_LEFT_PORT		GPIO_PORT_C
#define K2_DPAD_LEFT_PIN		GPIO_PIN8
#define K2_DPAD_UP_PORT			GPIO_PORT_C
#define K2_DPAD_UP_PIN			GPIO_PIN9

#define K2_BUTTON_B_PORT		GPIO_PORT_C
#define K2_BUTTON_B_PIN			GPIO_PIN11
#define K2_BUTTON_HOME_PORT		GPIO_PORT_C
#define K2_BUTTON_HOME_PIN		GPIO_PIN12
#define K2_SHOULDER_LEFT_PORT		GPIO_PORT_C
#define K2_SHOULDER_LEFT_PIN		GPIO_PIN13

#define K2_EXT_POWER_PORT		GPIO_PORT_C
#define K2_EXT_POWER_PIN		GPIO_PIN14

#define K2_HEADPHONE_JACK_PORT		GPIO_PORT_C
#define K2_HEADPHONE_JACK_PIN		GPIO_PIN18

/*
 * MADRID BOARD DEFINES
 */
#define MADRID_TOUCHSCREEN_X1_PORT	GPIO_PORT_A
#define MADRID_TOUCHSCREEN_X1_PIN	GPIO_PIN11
#define MADRID_TOUCHSCREEN_Y1_PORT	GPIO_PORT_A
#define MADRID_TOUCHSCREEN_Y1_PIN	GPIO_PIN12
#define MADRID_TOUCHSCREEN_X2_PORT	GPIO_PORT_A
#define MADRID_TOUCHSCREEN_X2_PIN	GPIO_PIN13
#define MADRID_TOUCHSCREEN_Y2_PORT	GPIO_PORT_A
#define MADRID_TOUCHSCREEN_Y2_PIN	GPIO_PIN14

#define MADRID_CARTRIDGE_DETECT_PORT	GPIO_PORT_A
#define MADRID_CARTRIDGE_DETECT_PIN	GPIO_PIN18

/* NO backlight enable pin */
//#define MADRID_LED_ENA_PORT		GPIO_PORT_A
//#define MADRID_LED_ENA_PIN		GPIO_PIN30

#define MADRID_VIBRATE_PORT		GPIO_PORT_A
#define MADRID_VIBRATE_PIN		GPIO_PIN30

#define MADRID_DPAD_DOWN_PORT		GPIO_PORT_A
#define MADRID_DPAD_DOWN_PIN		GPIO_PIN29

#define MADRID_DPAD_RIGHT_PORT		GPIO_PORT_C
#define MADRID_DPAD_RIGHT_PIN		GPIO_PIN3
#define MADRID_BUTTON_VOLUMEDOWN_PORT	GPIO_PORT_C
#define MADRID_BUTTON_VOLUMEDOWN_PIN	GPIO_PIN14

/* NO 'A', 'Pause', or 'Hint' button */
//#define MADRID_BUTTON_A_PORT		GPIO_PORT_C
//#define MADRID_BUTTON_A_PIN		GPIO_PIN3
//#define MADRID_BUTTON_PAUSE_PORT	GPIO_PORT_C
//#define MADRID_BUTTON_PAUSE_PIN	GPIO_PIN4
//#define MADRID_BUTTON_HINT_PORT	GPIO_PORT_C
//#define MADRID_BUTTON_HINT_PIN	GPIO_PIN5

/* No 'right shoulder' button */
//#define MADRID_SHOULDER_RIGHT_PORT	GPIO_PORT_C
//#define MADRID_SHOULDER_RIGHT_PIN	GPIO_PIN6


#define MADRID_BUTTON_VOLUMEUP_PORT	GPIO_PORT_C
#define MADRID_BUTTON_VOLUMEUP_PIN	GPIO_PIN2

#define MADRID_DPAD_LEFT_PORT		GPIO_PORT_A
#define MADRID_DPAD_LEFT_PIN		GPIO_PIN28

#define MADRID_DPAD_UP_PORT		GPIO_PORT_C
#define MADRID_DPAD_UP_PIN		GPIO_PIN4

/* No 'brightness' or 'B' button */
//#define MADRID_BUTTON_BRIGHTNESS_PORT	GPIO_PORT_C
//#define MADRID_BUTTON_BRIGHTNESS_PIN	GPIO_PIN10
//#define MADRID_BUTTON_B_PORT		GPIO_PORT_C
//#define MADRID_BUTTON_B_PIN		GPIO_PIN11
//#define MADRID_BUTTON_HOME_PORT	GPIO_PORT_C
//#define MADRID_BUTTON_HOME_PIN	GPIO_PIN6

/* New escape button (menu-ish) */
#define MADRID_BUTTON_ESC_PORT		GPIO_PORT_C
#define MADRID_BUTTON_ESC_PIN		GPIO_PIN6

/* No 'left shoulder' button */
//#define MADRID_SHOULDER_LEFT_PORT	GPIO_PORT_C
//#define MADRID_SHOULDER_LEFT_PIN	GPIO_PIN13

#define MADRID_HEADPHONE_JACK_PORT	GPIO_PORT_C
#define MADRID_HEADPHONE_JACK_PIN	GPIO_PIN10

#define MADRID_EXT_POWER_PORT		GPIO_PORT_C
#define MADRID_EXT_POWER_PIN		GPIO_PIN12

/*
 * Cartridge Board defines
 */
#define LIBERTAS_SPI_INTERRUPT_PORT	GPIO_PORT_B
#define LIBERTAS_SPI_INTERRUPT_PIN	GPIO_PIN4

#define LIBERTAS_SPI_RESET_PORT		GPIO_PORT_B
#define LIBERTAS_SPI_RESET_PIN		GPIO_PIN3

#endif	/* __GPIO_MAP_H__ */
