#!/bin/sh

# This script mounts misc volumes late (after AppManager starts)

report ()
{
	if [ $1 = 0 ]; then
		echo "Success"
	else
		#echo $2
		logger -s -t "Emerald Base" -p local4.err $2
	fi
}

tuneup ()
{
	logger -s -t "/etc/init.d/mounts" -p local4.notice "Failed bulk mount.  We're sick... tune up!  Setting panic to 3"
	echo 3 > /sys/devices/platform/lf1000-gpio/panic
	# Force a reboot that does not run /etc/init.d/shutdown, which will clear panic.  
	# See similar code in the old /usr/bin/app.  Not there now.
	sync
	sleep 1
	reboot -f
	# exit 1
}

get_ud ()
{
	# Without a loop, walk sys/class/ubi looking for ubi_bulk and set ud to the ubi#
	ud=`find /sys/class/ubi -name name | \
		xargs awk "/$1/ { x=split(FILENAME,y,\"/\"); print y[x-2] }" | \
		sed -e 's/ubi//'`
}

DAVE=/tmp/bulk_ready
MOUNT_PT=/LF/Bulk
UV=ubi_bulk

case "$1" in
	start)
		# Early out if already mounted
		if grep $MOUNT_PT /proc/mounts > /dev/null; then
			report 1 "$UV already mounted"
			exit 0;
		fi
		# Easy mount for SD cards
		if grep rootfstype=ext3 /proc/cmdline; then
			report 1 "`tim begin 'Mounting SD /LF/Bulk'`"
			mount -o noatime /dev/mmcblk0p4 /LF/Bulk
			report $? "Failed mount of mmcblk0p4 from /LF/Bulk"
			# Signal /LF/Bulk ready to AppManager
			echo 1 > $DAVE
			report 1 "`tim end 'Mounting SD /LF/Bulk'`"
			exit 0;
		fi
		# Attach if needed
		get_ud "$UV"
		if [ -z "$ud" ]; then
			report 1 "`tim begin 'Attaching Bulk'`"
			mn=`awk -F: '/Bulk/ {print substr($1,4)}' /proc/mtd`
			ubiattach /dev/ubi_ctrl -m $mn
			if [ $? != 0 ]; then
				report 1 "Failed ubiattach for mtd$mn!"
				tuneup
			fi
			get_ud "$UV"
			if [ -z "$ud" ]; then
				report 1 "Failed to find $UV in /sys!  Impossible!!!"
				tuneup
			fi
		fi
		# Mount ubi$ud:$UV
		where=$MOUNT_PT
		report 1 "`tim begin \"Mounting $where ubi$ud\"`"
		mount -t ubifs -o rw ubi${ud}:${UV} $where
		if [ $? != 0 ]; then		
			report 1 "Failed mount of ubi${ud}:${UV} to $where"
			tuneup
		fi
		# Tell Dave!  1=bulk is ready and good, 0 is it will never be ready,
		# and no file is not ready yet.
		echo 1 > $DAVE
		report 1 "`tim end \"Mounting $where ubi$ud\"`"
		;;
	stop)
		# Easy umount for SD cards
		if grep rootfstype=ext3 /proc/cmdline; then
			report 1 "`tim begin 'Unmounting SD /LF/Bulk'`"
			umount /dev/mmcblk0p4
			report $? "Failed umount of mmcblk0p4 from /LF/Bulk"
			report 1 "`tim end 'Unmounting SD /LF/Bulk'`"
			exit 0;
		fi
		# More work for UBI
		get_ud "$UV"
		if [ -z "$ud" ]; then
			report 1 "Failed to find $UV in /sys!"
		else
			if grep $MOUNT_PT /proc/mounts > /dev/null; then 
				report 1 "umount $MOUNT_PT..."
				umount $MOUNT_PT; 
				report $? "Failed umount of ubi${ud} from $MOUNT_PT"
			else
				report 1 "$MOUNT_PT not mounted"
			fi
			if [ -e /sys/class/ubi/ubi$ud ]; then
				report 1 "ubidetach $ud..."
				ubidetach /dev/ubi_ctrl -d $ud
				report $? "Failed to ubidetach $ud"
			fi
			rm -f $DAVE
		fi
		;;

	restart)
		report 1 "restart mounting bulk... !"	
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
