#!/bin/sh

random_digits ()
{
	string=$RANDOM
	A=${string:$((${#string}-1)):1}
	string=$RANDOM
	B=${string:$((${#string}-1)):1}
	string=$RANDOM
	C=${string:$((${#string}-1)):1}
	string=$RANDOM
	D=${string:$((${#string}-1)):1}
	string=$RANDOM
	E=${string:$((${#string}-1)):1}
}

case "$1" in
	start)
		logger -s -t "Emerald Base" -p local4.notice  "Starting Ethernet USB driver ..."
		host_addr=`mfgdata get host`
		dev_addr=`mfgdata get device`
		serial_number=`mfgdata get sn`
		if [ -z "$host_addr" ] || \
		   [ "$host_addr" = "80:38:FD:80:00:00" ]; then
			echo "host_addr=$host_addr"
			random_digits
			host_addr="80:38:FD:8$A:$B$C:$D$E"
			dev_addr="80:38:FD:0$A:$B$C:$D$E"
		serial_number="0"
		fi
		modprobe g_ether host_addr=$host_addr \
				 dev_addr=$dev_addr \
				 iSerialNumber=$serial_number
;;
	stop)
		logger -s -t "Emerald Base" -p local4.notice  "Stopping Ethernet USB driver ..."	
		ifconfig usb0 down
		modprobe -r g_ether
		;;
	restart)
		logger -s -t "Emerald Base" -p local4.notice  "Restarting Ethernet USB driver ..."
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
                                                        
exit 0
